name: Pull Request Validation

on:
  pull_request:
    branches: 
      - main
      - develop
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate user social links
        if: contains(github.event.pull_request.changed_files, 'users/')
        run: |
          # Check if users directory exists
          if [ -d "users" ]; then
            for file in users/*.yml users/*.yaml; do
              if [ -f "$file" ]; then
                echo "Validating $file..."
                if ! grep -q 'linkedin:' "$file" || ! grep -q 'github:' "$file"; then
                  echo "Error: $file must contain both 'linkedin:' and 'github:' fields."
                  exit 1
                fi
                echo "✓ $file is valid"
              fi
            done
          fi

      - name: Validate code quality
        run: |
          echo "Running basic code validation..."
          
          # Check for common issues
          echo "Checking for merge conflict markers..."
          if grep -r "<<<<<<< HEAD\|=======" --include="*.js" --include="*.jsx" --include="*.ts" --include="*.tsx" --include="*.py" --include="*.md" .; then
            echo "Error: Merge conflict markers found in files"
            exit 1
          fi
          
          echo "✓ No merge conflicts found"

      - name: Check PR requirements
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Description length: $(echo '${{ github.event.pull_request.body }}' | wc -c)"
          
          # Ensure PR has a meaningful title (more than 10 characters)
          if [ ${#PR_TITLE} -lt 10 ]; then
            echo "Error: PR title must be at least 10 characters long"
            exit 1
          fi
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}