name: Branch Protection Setup

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - master
    paths:
      - '.github/workflows/branch-protection.yml'

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch protection
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Branches to protect
            const branchesToProtect = ['master'];
            
            for (const branch of branchesToProtect) {
              try {
                // Check if branch exists
                try {
                  await github.rest.repos.getBranch({
                    owner,
                    repo,
                    branch
                  });
                } catch (error) {
                  if (error.status === 404) {
                    console.log(`Branch '${branch}' does not exist, skipping...`);
                    continue;
                  }
                  throw error;
                }
                
                // Apply protection rules
                await github.rest.repos.updateBranchProtection({
                  owner,
                  repo,
                  branch,
                  required_status_checks: {
                    strict: true,
                    contexts: ['validate-changes']
                  },
                  enforce_admins: false,
                  required_pull_request_reviews: {
                    required_approving_review_count: 1,
                    dismiss_stale_reviews: true,
                    require_code_owner_reviews: false,
                    require_last_push_approval: false
                  },
                  restrictions: null,
                  allow_force_pushes: false,
                  allow_deletions: false,
                  block_creations: false,
                  required_conversation_resolution: true
                });
                
                console.log(`✅ Branch protection rules updated successfully for '${branch}'`);
              } catch (error) {
                console.log(`❌ Error setting up branch protection for '${branch}':`, error.message);
                console.log('Note: This might fail if you do not have admin permissions on the repository');
              }
            }
